# ===================================================================
# Spring Boot configuration for the "azure" profile.
#
# This configuration overrides the application.yml file.
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

azure:
  application-insights:
    instrumentation-key: fa2285ae-23fe-451f-b4b4-75af3f6d8b0e
